---
- hosts: all
  name: provision test host running eth2 validator
  become: yes
  become_method: sudo

  # it is recommended that you override the defaults below. Most settings that you can
  # override here can be found in roles/validator/defaults/main.yml
  vars:
    network: 'pyrmont'  # set up an environment for the testnet

    # if you want to install a local ETH1 node, use the configuration below.
    # If you want to connect to an external node, you can comment out
    # the next 4 lines
    install_eth1_node: yes
    geth_network_id: 5  # 5 = Görli
    geth_bootnodes: "enode://df85d47ef311c7563c9e7d095799d5033d8732c21c3df9cc8d89a8b6f82dd5ea95e3ebcc129d5fc91961c6f0b827937279812cbf839d92e39a3e8362d210ce05@173.212.232.153:30303,enode://4fcfd895fe18c51b763a016112e2ac094a1eba8668eda0e833bc0d772d4d94575e4fb01f38390ee3f0c39ec0289ecd64032160c4b083c18a7f5816b50e50c30a@221.12.141.194:30303"
    # if you want to connect to an external ETH1 node, uncomment the following line
    # and provide the url to a node.
    # web3_provider: https://mainnet.infura.io/v3/yourserverid

    validator_password: validatorPass
    validator_graffiti: 'set your graffiti string here'

    # URL at which grafana will be available
    grafana_url: "http://localhost"
    # password for Grafana UI access (username will be 'admin')
    grafana_password: grafanaAdmin

    # for testnet, you may want to run eth2stats
    install_eth2stats: yes
    eth2stats_nodename: myethstats_nodename # change this to something unique for you

    # your cryptowat config
    cryptowat_pairs: ethusd,ethbtc,etheur
    cryptowat_exchanges: kraken

  roles:
     - { role: validator }
