---
- hosts: all
  name: provision test host running eth2 validator in VirtualBox VM image
  become: yes
  become_method: sudo

  # This is an example setup for running the Prysm beaconchain in a VirtualBox
  # VM. This example does not install/run an Eth1 node, but uses an infura
  # node instead.

  vars:
    network: 'pyrmont'  # change to 'mainnet' for mainnet setup
    install_eth1_node: no

    # this is the wallet password for the wallet generated on your server.
    # It should be different from your keystore password that you set when you generated the keys.
    wallet_password: 'CHANGEME'
    validator_graffiti: 'Vagrant test node'

    # connect to an external Eth1 node.
    web3_provider: https://goerli.prylabs.net/

    # URL at which grafana will be available
    grafana_url: "http://localhost"
    # password for Grafana UI access (username will be 'admin')
    grafana_password: grafanaAdmin

    # you're probably just testing so no need to send stats to eth2stats
    install_eth2stats: no
    eth2stats_nodename: vagrant_test

    cryptowat_pairs: ethusd,ethbtc,etheur
    cryptowat_exchanges: kraken

  roles:
     - { role: validator }
