---
- hosts: all
  name: provision test host running eth2 validator
  become: yes
  become_method: sudo

  # it is recommended that you override the defaults below. Most settings that you can
  # override here can be found in roles/validator/defaults/main.yml
  vars:
    network: 'pyrmont'  # set up an environment for the testnet

    # if you want to install a local ETH1 node, enable the following property.
    # Your beaconchain will automatically be configured to use your local node.
    # Set to 'no' if you have limited server resources and/or harddisk and want to
    # sync to an external node.
    install_eth1_node: yes
    # only applies when running a local eth1 node:
    geth_network_id: 5  # 5 = Görli
    # geth_bootnodes: "enode://..."  # you can provide a bootnodes list if you are having problems finding peers
    #
    # If install_eth1_node is 'no', configure your web3 provider below.
    # web3_provider: https://mainnet.infura.io/v3/yourserverid

    validator_password: validatorPass
    validator_graffiti: 'set your graffiti string here'

    # URL at which grafana will be available
    grafana_url: "http://localhost"
    # password for Grafana UI access (username will be 'admin')
    grafana_password: grafanaAdmin

    # for testnet, you may want to run eth2stats
    install_eth2stats: yes
    eth2stats_nodename: myethstats_nodename # change this to something unique for you

    # your cryptowat config
    cryptowat_pairs: ethusd,ethbtc,etheur
    cryptowat_exchanges: kraken

  roles:
     - { role: validator }
