---
- hosts: all
  name: provision production host running eth2 validator
  become: yes
  become_method: sudo

  # it is recommended that you override the defaults below. Most settings that you can
  # override here can be found in roles/validator/defaults/main.yml
  vars:
    network: 'mainnet'  # set up an environment for the mainnet

    # if you want to install a local ETH1 node, enable the following property.
    # Your beaconchain will automatically be configured to use your local node.
    # Set to 'no' if you have limited server resources and/or harddisk and want to
    # sync to an external node.
    install_eth1_node: yes
    # only applies when running a local eth1 node:
    geth_network_id: 1  # set mainnet
    # you can provide a bootnodes list if you are having problems finding peers
    #geth_bootnodes: "enode://df85d47ef311c7563c9e7d095799d5033d8732c21c3df9cc8d89a8b6f82dd5ea95e3ebcc129d5fc91961c6f0b827937279812cbf839d92e39a3e8362d210ce05@173.212.232.153:30303,enode://4fcfd895fe18c51b763a016112e2ac094a1eba8668eda0e833bc0d772d4d94575e4fb01f38390ee3f0c39ec0289ecd64032160c4b083c18a7f5816b50e50c30a@221.12.141.194:30303"
    #
    # If install_eth1_node is 'no', configure your web3 provider below.
    # web3_provider: https://mainnet.infura.io/v3/yourserverid

    # You can leave this to the default 30 but I found 60 to work better for mainnet
    # if you have a few validators
    beaconchain_max_peers: 60

    # this is the wallet password for the wallet generated on your server.
    # It should be different from your keystore password that you set when you generated the keys.
    wallet_password: 'CHANGEME'

    validator_graffiti: 'set your graffiti string here'

    # URL at which grafana will be available
    grafana_url: "http://localhost"
    # password for Grafana UI access (username will be 'admin')
    grafana_password: grafanaAdmin

    # your cryptowat config
    cryptowat_pairs: ethusd,ethbtc,etheur
    cryptowat_exchanges: kraken

  roles:
     - { role: validator }
