---
- name: Add the Bazel Apt signing key
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present

- name: install Bazel apt repository
  apt_repository:
    repo: deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
    state: present
    filename: bazel

- name: Install Bazel packages
  apt:
    name: ['bazel','bazel-3.2.0']
    state: present
