---

- include: packages.yml

- include: firewall.yml

- include: geth/main.yml
  when: install_eth1_node

# This can be used to make sure geth is stopped and disabled if geth config
# is changed, but will fail if geth was never installed.
# - systemd:
#     name: geth
#     state: stopped
#     enabled: no
#   when: not install_eth1_node  # in case it was installed before

- include: prysm/prysm.yml
  when: eth2client == "Prysm"

- include: lighthouse/lighthouse.yml
  when: eth2client == "Lighthouse"

- include: metrics/metrics.yml
